name: Enforce PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check all checklist items are checked
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || '';
            if (body.match(/- \[ \]/)) {
              core.setFailed('Please check all items in the PR checklist before merging.');
            }